controller_list:
 - name: arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - base_arm_to_base2
      - base_to_shoulder
      - shoulder_to_elbow
      - elbow_to_wrist
      - wrist_to_grip_base
 - name: gripper_controller
   action_ns: gripper_action
   type: GripperCommand
   default: true
   joints:
      - grip_base_to_right_finger


